### ISSUE TITLE
Defining 'cls.syntax' has been deprecated

### ISSUE THREAD

**Issue by tszulc** [jhoff/SublimeLinter-contrib-php-cs-fixer#8]
When loading SublimeLinter-rubocop.linter, this error can be seen in Sublime's console:

```
SublimeLinter: ERROR:
=====================

phpcsfixer: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

phpcsfixer disabled. 'cls.defaults' is mandatory and MUST be a dict.
```

Same issue was experienced by other SublimeLinter plugins:
maristgeek/SublimeLinter-contrib-bashate#17
SublimeLinter/SublimeLinter-html-tidy#56

And were resolved like this:
maristgeek/SublimeLinter-contrib-bashate@0500219
SublimeLinter/SublimeLinter-html-tidy@3da0310

**Comment by knagode** [comment]
How to resolve this?

**Comment by tszulc** [comment]
I made a PR that should solve the issue: jhoff/SublimeLinter-contrib-php-cs-fixer#9

**Comment by jhoff** [comment]
This should be resolved
